// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: body/test.proto

package body

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TestMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Value         int64                  `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestMessage) Reset() {
	*x = TestMessage{}
	mi := &file_body_test_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestMessage) ProtoMessage() {}

func (x *TestMessage) ProtoReflect() protoreflect.Message {
	mi := &file_body_test_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestMessage.ProtoReflect.Descriptor instead.
func (*TestMessage) Descriptor() ([]byte, []int) {
	return file_body_test_proto_rawDescGZIP(), []int{0}
}

func (x *TestMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TestMessage) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

var File_body_test_proto protoreflect.FileDescriptor

const file_body_test_proto_rawDesc = "" +
	"\n" +
	"\x0fbody/test.proto\x12\x04body\"3\n" +
	"\vTestMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05valueB\"Z github.com/skyrocket-qy/gox/bodyb\x06proto3"

var (
	file_body_test_proto_rawDescOnce sync.Once
	file_body_test_proto_rawDescData []byte
)

func file_body_test_proto_rawDescGZIP() []byte {
	file_body_test_proto_rawDescOnce.Do(func() {
		file_body_test_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_body_test_proto_rawDesc), len(file_body_test_proto_rawDesc)))
	})
	return file_body_test_proto_rawDescData
}

var file_body_test_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_body_test_proto_goTypes = []any{
	(*TestMessage)(nil), // 0: body.TestMessage
}
var file_body_test_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_body_test_proto_init() }
func file_body_test_proto_init() {
	if File_body_test_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_body_test_proto_rawDesc), len(file_body_test_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_body_test_proto_goTypes,
		DependencyIndexes: file_body_test_proto_depIdxs,
		MessageInfos:      file_body_test_proto_msgTypes,
	}.Build()
	File_body_test_proto = out.File
	file_body_test_proto_goTypes = nil
	file_body_test_proto_depIdxs = nil
}
